import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const material = new THREE.MeshStandardMaterial();

export function Column({ castShadow = false, ...props }) {
  const { nodes } = useGLTF("./model.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_1.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_2.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_3.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_4.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_5.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_6.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_7.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_8.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_9.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_10.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_11.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_12.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_13.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_14.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_15.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_16.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_17.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_18.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_19.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_20.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_21.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_22.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_23.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_24.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_25.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_26.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_27.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_28.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_29.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_30.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_31.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_32.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_33.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_34.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_35.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_36.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_37.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_38.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_39.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_40.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_41.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_42.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_43.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_44.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_45.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_46.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_47.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_48.geometry}
        material={material}
      />
      <mesh
        castShadow={castShadow}
        geometry={nodes.mesh_3_49.geometry}
        material={material}
      />
    </group>
  );
}

useGLTF.preload("/model.glb");
