/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/play3.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Play3(props) {
  const { nodes, materials } = useGLTF('/play3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_1.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_2.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_3.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_4.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_5.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_6.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_7.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_8.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_9.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_10.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_11.geometry} material={materials['western-red-cedar-3229-mm-architextures']} />
      <mesh geometry={nodes.mesh_14.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_15.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_16.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_17.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_18.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_19.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_20.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_21.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_22.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_23.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_24.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_25.geometry} material={materials['aerial-wallpaper-in-birch-1040-mm-architextures']} />
      <mesh geometry={nodes.mesh_30.geometry} material={materials.dc9reK7qi} />
      <mesh geometry={nodes.mesh_31.geometry} material={materials['Paint (1)']} />
      <mesh geometry={nodes.mesh_32.geometry} material={materials.Paint} />
      <mesh geometry={nodes.mesh_33.geometry} material={materials['Paint (1)']} />
      <mesh geometry={nodes.mesh_36.geometry} material={materials['moss-300-mm-architextures']} />
      <mesh geometry={nodes.mesh_37.geometry} material={materials['Paint (3)']} />
      <mesh geometry={nodes.mesh_12.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_12_1.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_12_2.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_12_3.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_12_4.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_12_5.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_13.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_13_1.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_13_2.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_13_3.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_13_4.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_13_5.geometry} material={materials.Flowers} />
      <mesh geometry={nodes.mesh_26.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_26_1.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_26_2.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_26_3.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_26_4.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_26_5.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27_1.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27_2.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27_3.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27_4.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_27_5.geometry} material={materials['Paint (4)']} />
      <mesh geometry={nodes.mesh_28.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_1.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_2.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_3.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_4.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_5.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_6.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_7.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_8.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_9.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_10.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_11.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_12.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_13.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_14.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_15.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_16.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_17.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_18.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_19.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_20.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_21.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_22.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_23.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_24.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_25.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_26.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_27.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_28.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_29.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_30.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_31.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_32.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_33.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_34.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_35.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_36.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_37.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_38.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_39.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_40.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_41.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_42.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_43.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_44.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_45.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_46.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_47.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_48.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_28_49.geometry} material={materials['Paint (6)']} />
      <mesh geometry={nodes.mesh_29.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_1.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_2.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_3.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_4.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_5.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_6.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_7.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_8.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_9.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_10.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_11.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_12.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_13.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_14.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_15.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_16.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_17.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_18.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_19.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_20.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_21.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_22.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_23.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_24.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_25.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_26.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_27.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_28.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_29.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_30.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_31.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_32.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_33.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_34.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_35.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_36.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_37.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_38.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_39.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_40.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_41.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_42.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_43.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_44.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_45.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_46.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_47.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_48.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_29_49.geometry} material={materials.Custom} />
      <mesh geometry={nodes.mesh_34.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_34_1.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_34_2.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_34_3.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_34_4.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_34_5.geometry} material={materials['boardmarked-in-situ-concrete-4000-mm-architextures']} />
      <mesh geometry={nodes.mesh_35.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_35_1.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_35_2.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_35_3.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_35_4.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
      <mesh geometry={nodes.mesh_35_5.geometry} material={materials['Screenshot 2023-12-11 at 21.22.50']} />
    </group>
  )
}

useGLTF.preload('/play3.gltf')
